-- MySQL Script generated by MySQL Workbench
-- Wed Apr  1 10:47:39 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema covid_19
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema covid_19
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `covid_19` DEFAULT CHARACTER SET utf8 ;
USE `covid_19` ;

-- -----------------------------------------------------
-- Table `covid_19`.`DIM_COUNTRY_REGION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covid_19`.`DIM_COUNTRY_REGION` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `covid_19`.`DIM_LOCATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covid_19`.`DIM_LOCATION` (
  `ID` INT NOT NULL,
  `ID_COUNTRY_REGION` INT NULL,
  `PROVINCE_STATE` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_COUNTRY_idx` (`ID_COUNTRY_REGION` ASC) VISIBLE,
  CONSTRAINT `FK_COUNTRY`
    FOREIGN KEY (`ID_COUNTRY_REGION`)
    REFERENCES `covid_19`.`DIM_COUNTRY_REGION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `covid_19`.`DIM_DATE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covid_19`.`DIM_DATE` (
  `ID` INT NOT NULL,
  `DATE` VARCHAR(45) NULL,
  `YEAR` VARCHAR(45) NULL,
  `MONTH` VARCHAR(45) NULL,
  `DAY` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `covid_19`.`FACT_COVID_19_DATA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covid_19`.`FACT_COVID_19_DATA` (
  `ID` INT NOT NULL,
  `ID_DATE` INT NULL,
  `ID_LOCATION` INT NULL,
  `CONFIRMED` INT NULL,
  `DEATHS` INT NULL,
  `RECOVERED` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_LOCATION_idx` (`ID_LOCATION` ASC) VISIBLE,
  INDEX `FK_DATE_idx` (`ID_DATE` ASC) VISIBLE,
  CONSTRAINT `FK_LOCATION`
    FOREIGN KEY (`ID_LOCATION`)
    REFERENCES `covid_19`.`DIM_LOCATION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_DATE`
    FOREIGN KEY (`ID_DATE`)
    REFERENCES `covid_19`.`DIM_DATE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
